---
title: "Figure 6, Table S1, S2, S3"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
rm(list = ls())
library(reticulate)
library(readxl)
library(tidyverse)
library(nloptr)
# library(phyloseq)
library(stringr)
library(ggpubr)
library(magrittr)
library(qwraps2)
library(pander)
panderOptions('table.caption.prefix', NULL)
panderOptions('table.continues', NULL)
panderOptions('table.emphasize.rownames', FALSE)

source("~/metaanalysis/datasets/ancom_bc.R")
```

```{python}
import pandas as pd
import numpy as np
from IPython.display import display
```
# 1. Feature Table Construction

## 1.1 Meta data

```{r, message=FALSE, warning=FALSE, comment=NA}
# Read in meta data
meta_data = read_tsv("/home/odeds/metaanalysis/datasets/MetaHit/Study.design.tab")
meta_data=meta_data%>%transmute(Sample.ID=Sample, age=Age, sex=Gender, country=Country, diagnosis= IBD)%>%
  arrange(Sample.ID)
meta_data=meta_data[complete.cases(meta_data), ]
meta_data$age=as.numeric(meta_data$age)
meta_data$country=recode(meta_data$country, `GAZ:Spain` = "Spain", 
                         `GAZ:Denmark` = "Denmark")
meta_data$diagnosis=recode(meta_data$diagnosis, `Y`="IBD", `N`="Control")
```

```{python}
taxonomy_OTU = pd.read_csv("/home/odeds/metaanalysis/datasets/species_abundance/MetaHit_species_abundance.csv").set_index('Abundance').T
prefix_map = {
    's__': 'Species',
    'g__': 'Genus',
    'f__': 'Family',
    'o__': 'Order',
    'c__': 'Class',
    'p__': 'Phylum',
    'k__': 'Kingdom',
    't__': 'Strain'
}

new_data = {}
for prefix, new_col in prefix_map.items():
    relevant_columns = [col for col in taxonomy_OTU.columns if col.startswith(prefix)]
    if relevant_columns:
        new_data[new_col] = relevant_columns

max_len = max(len(cols) for cols in new_data.values())

for key, val in new_data.items():
    while len(new_data[key]) < max_len:
        new_data[key].append(None)

taxonomy = pd.DataFrame(new_data)

dfs = {}

for prefix, taxon in prefix_map.items():
    dfs[taxon] = taxonomy_OTU[[col for col in taxonomy_OTU.columns if col.startswith(prefix)]]

Species_table = dfs['Species'].T.reset_index()
Genus_table = dfs['Genus'].T.reset_index()
Family_table = dfs['Family'].T.reset_index()
Order_table = dfs['Order'].T.reset_index()
Class_table = dfs['Class'].T.reset_index()
Phylum_table = dfs['Phylum'].T.reset_index()
Kingdom_table = dfs['Kingdom'].T.reset_index()
Strain_table = dfs['Strain'].T.reset_index()
```

## 1.2 Supplementary Table 2


# 2. Differential Abundance (DA) Analysis

## 2.1 CD vs nonIBD vs UC 

### 2.1.1 IBD vs Control by female 

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
# Subset meta data
meta.data=meta_data%>%filter(diagnosis%in%c("IBD", "Control") , sex%in%c("female")) # age<40 
meta.data$country=as.character(meta.data$diagnosis)
pander(table(meta.data$diagnosis))
# Subset OTU table
obs.abn=py$Species_table
rownames(obs.abn)=obs.abn$Abundance
#obs.abn=obs.abn[, -1]
obs.abn=obs.abn[, meta.data$Sample.ID]
# Recode sample ID
meta.data$Sample.ID=seq(nrow(meta.data))
colnames(obs.abn)=seq(nrow(meta.data))

# Pre-Processing
feature.table=obs.abn; sample.var="Sample.ID"; group.var="diagnosis"; 
feature.table[is.na(feature.table)] = 0 
feature.table = feature.table * 1000000
zero.cut=0.90; lib.cut=1000; neg.lb=TRUE

pre.process=feature_table_pre_process(feature.table, meta.data, sample.var, group.var, 
                                      zero.cut, lib.cut, neg.lb)

feature.table=pre.process$feature.table
library.size=pre.process$library.size
group.name=pre.process$group.name
group.ind=pre.process$group.ind
struc.zero=pre.process$structure.zeros

# Paras for ANCOM-BC
grp.name=group.name; grp.ind=group.ind; adj.method="bonferroni"
tol.EM=1e-5; max.iterNum=100; perNum=1000; alpha=0.05

# Run ANCOM-BC
start_time <- Sys.time()
out=ANCOM_BC(feature.table, grp.name, grp.ind, struc.zero, adj.method, 
             tol.EM, max.iterNum, perNum, alpha)
end_time <- Sys.time()
end_time - start_time

# Test result
res.ANCOM_BC=data.frame(phylum=rownames(out$feature.table), out$res, 
                        struc.zero[rownames(out$feature.table), ], 
                        row.names = NULL, stringsAsFactors=FALSE, check.names = FALSE)
alpha.adj=0.05/nrow(res.ANCOM_BC)
critic.val=qnorm(1-alpha.adj/2)
res.ANCOM_BC=res.ANCOM_BC%>%transmute(phylum,
                                      `log fold change (IBD - Control)` = -`mean.difference (IBD - Control)`,
                                      se=`se (IBD - Control)`, 
                                      ci.lo.adj=`log fold change (IBD - Control)`-critic.val*se, 
                                      ci.up.adj=`log fold change (IBD - Control)`+critic.val*se, 
                                      p.val, q.val, diff.abn, 
                                      `structural.zero (IBD)`, 
                                      `structural.zero (Control)`)
res.ANCOM_BC_0=res.ANCOM_BC%>%arrange(q.val)
# write_csv(res.ANCOM_BC, "C:/Users/user/Desktop/ma_us_phylum_age2.csv")
```

### 2.1.2 IBD vs Control by male 

```{r, message=FALSE, warning=FALSE, comment=NA, eval=FALSE}
# Subset meta data
meta.data=meta_data%>%filter(diagnosis%in%c("IBD", "Control") , sex%in%c("male"))
meta.data$country=as.character(meta.data$diagnosis)
pander(table(meta.data$diagnosis))
# Subset OTU table
obs.abn=py$Phylum_table
rownames(obs.abn)=obs.abn$Abundance
#obs.abn=obs.abn[, -1]
obs.abn=obs.abn[, meta.data$Sample.ID]
# Recode sample ID
meta.data$Sample.ID=seq(nrow(meta.data))
colnames(obs.abn)=seq(nrow(meta.data))

# Pre-Processing
feature.table=obs.abn; sample.var="Sample.ID"; group.var="diagnosis"; 
feature.table[is.na(feature.table)] = 0 
feature.table = feature.table * 1000000
zero.cut=0.90; lib.cut=1000; neg.lb=TRUE

pre.process=feature_table_pre_process(feature.table, meta.data, sample.var, group.var, 
                                      zero.cut, lib.cut, neg.lb)

feature.table=pre.process$feature.table
library.size=pre.process$library.size
group.name=pre.process$group.name
group.ind=pre.process$group.ind
struc.zero=pre.process$structure.zeros

# Paras for ANCOM-BC
grp.name=group.name; grp.ind=group.ind; adj.method="bonferroni"
tol.EM=1e-5; max.iterNum=100; perNum=1000; alpha=0.05

# Run ANCOM-BC
start_time <- Sys.time()
out=ANCOM_BC(feature.table, grp.name, grp.ind, struc.zero, adj.method, 
             tol.EM, max.iterNum, perNum, alpha)
end_time <- Sys.time()
end_time - start_time

# Test result
res.ANCOM_BC=data.frame(phylum=rownames(out$feature.table), out$res, 
                        struc.zero[rownames(out$feature.table), ], 
                        row.names = NULL, stringsAsFactors=FALSE, check.names = FALSE)
alpha.adj=0.05/nrow(res.ANCOM_BC)
critic.val=qnorm(1-alpha.adj/2)
res.ANCOM_BC=res.ANCOM_BC%>%transmute(phylum,
                                      `log fold change (IBD - Control)` = -`mean.difference (IBD - Control)`,
                                      se=`se (IBD - Control)`, 
                                      ci.lo.adj=`log fold change (IBD - Control)`-critic.val*se, 
                                      ci.up.adj=`log fold change (IBD - Control)`+critic.val*se, 
                                      p.val, q.val, diff.abn, 
                                      `structural.zero (IBD)`, 
                                      `structural.zero (Control)`)
res.ANCOM_BC_1=res.ANCOM_BC%>%arrange(q.val)
# write_csv(res.ANCOM_BC, "C:/Users/user/Desktop/ma_us_phylum_age2.csv")
```
# 3. Plottings

## 3.1 IBD vs Control by sex

```{r, message=FALSE, warning=FALSE, comment=NA}
ma_us_0_2= res.ANCOM_BC_0
ma_us_18_40=res.ANCOM_BC_1
ma_us_phyla=unique(c(ma_us_0_2$phylum, ma_us_18_40$phylum))

ma_us_0_2=ma_us_0_2%>%transmute(phylum, log.fold.change=`log fold change (IBD - Control)`,
                                se=se, ci.lo=ci.lo.adj, ci.up=ci.up.adj,
                                struc.zero=ifelse(se==0, 1, 0), 
                                q.val, diagnosis.group = "IBD",
                                star=ifelse(q.val<.001, "***", 
                                                ifelse(q.val<.01, "**",
                                                       ifelse(q.val<.05, "*", ""))))
if(length(setdiff(ma_us_phyla, ma_us_0_2$phylum))>0){
  ma_us_0_2.1=data.frame(phylum=setdiff(ma_us_phyla, ma_us_0_2$phylum),
                         log.fold.change=0, se=0, ci.lo=0, ci.up=0, 
                         struc.zero=1, q.val=1, diagnosis.group="IBD", star="")
  ma_us_0_2=rbind(ma_us_0_2, ma_us_0_2.1)
}

ma_us_18_40=ma_us_18_40%>%transmute(phylum, log.fold.change=`log fold change (IBD - Control)`,
                                    se=se, ci.lo=ci.lo.adj, ci.up=ci.up.adj,
                                    struc.zero=ifelse(se==0, 1, 0), 
                                    q.val, diagnosis.group = "Control",
                                    star=ifelse(q.val<.001, "***", 
                                                ifelse(q.val<.01, "**",
                                                       ifelse(q.val<.05, "*", ""))))
if(length(setdiff(ma_us_phyla, ma_us_18_40$phylum))>0){
  ma_us_18_40.1=data.frame(phylum=setdiff(ma_us_phyla, ma_us_18_40$phylum),
                           log.fold.change=0, se=0, ci.lo=0, ci.up=0, 
                           struc.zero=1, q.val=1, diagnosis.group="Control", star="")
  ma_us_18_40=rbind(ma_us_18_40, ma_us_18_40.1)
}

dat.fig_ma_us=rbind(ma_us_0_2, ma_us_18_40)
dat.fig_ma_us$age.group=factor(dat.fig_ma_us$diagnosis.group, 
                               levels = c("IBD", "Control"))
dat.fig_ma_us$phylum=sapply(dat.fig_ma_us$phylum, function(x) strsplit(x, "__")[[1]][2])
dat.fig_ma_us$phylum=factor(dat.fig_ma_us$phylum, levels = sort(unique(dat.fig_ma_us$phylum)))
dat.fig_ma_us$struc.zero=factor(dat.fig_ma_us$struc.zero)
```

## 3.2 Fig. 1a

```{r, message=FALSE, warning=FALSE, comment=NA, fig.height=5, fig.width=10}
dat.fig_ma_us2=cbind(dat.fig_ma_us, type="Female-Male")
# dat.fig_ven_us2=cbind(dat.fig_ma_us, type="2")
# dat.fig_ma_ven2=cbind(dat.fig_ma_us, type="3")
#dat.fig_ma_ven2=dat.fig_ma_ven2[-which(dat.fig_ma_ven2$phylum%in%c("Acidobacteria", "Chloroflexi")), ]
#dat.fig_ma_ven2$phylum=factor(dat.fig_ma_ven2$phylum)

dat.fig=rbind(dat.fig_ma_us2,dat.fig_ma_us2)#, dat.fig_ven_us2)#, dat.fig_ma_ven2)
dat.fig$type=factor(dat.fig$type, levels = c("Female-Male"))#, "2", "3"))

p1=ggplot(dat.fig, aes(x=phylum, y=log.fold.change, ymin=ci.lo, ymax=ci.up, group=diagnosis.group)) + 
  geom_bar(aes(fill=age.group), stat="identity", width=0.4, position=position_dodge())+
  geom_errorbar(width=0.2, size=0.25, position=position_dodge(width = 0.4))+
  geom_abline(slope = 0, intercept = 0, linetype="dashed", alpha=0.5)+
  labs(x=NULL, y="Log Fold Change")+coord_flip()+
  scale_fill_discrete(name=NULL)+
  scale_x_discrete(limits = rev(levels(dat.fig$phylum)))+
  facet_grid(.~type, scales = "free_x")+
  theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill="white"))+
  geom_text(aes(y=log.fold.change+4*sign(log.fold.change), label=star), 
            vjust=.7, color="black", position=position_dodge(width = .5))
p1 = p1+geom_point(data = dat.fig%>%filter(struc.zero==1), aes(x=phylum, y=log.fold.change),
                   position=position_dodge(width = 0.4), shape=18)
ggarrange(p1, labels = "a")
# ggsave("C:/Users/user/Figure 6a.pdf", width=10, height=5, units='in')
# ggsave("C:/Users/user/Figure 6a.jpeg", width=10, height=5, units='in', dpi = 300)
```


## 3.3 Fig. 1b

```{r, message=FALSE, warning=FALSE, comment=NA, fig.height=5, fig.width=6.25}
dat.fig.diff=BFres
dat.fig.diff$log.fold.change=as.numeric(dat.fig.diff$log.fold.change)
dat.fig.diff$ci.lo=as.numeric(dat.fig.diff$ci.lo)
dat.fig.diff$ci.up=as.numeric(dat.fig.diff$ci.up)
dat.fig.diff$p.value=as.numeric(dat.fig.diff$p.value)
dat.fig.diff=dat.fig.diff%>%mutate(star=ifelse(p.value<.001, "***", 
                                               ifelse(p.value<.01, "**",
                                                      ifelse(p.value<.05, "*", ""))))

p2=ggplot(dat.fig.diff, aes(x=country, y=log.fold.change, ymin=ci.lo, ymax=ci.up, group=age)) + 
  geom_bar(aes(fill=age), 
           stat="identity", width=0.4, position=position_dodge())+
  geom_errorbar(width=.2, size=.25, position=position_dodge(width = .4))+
  geom_abline(slope = 0, intercept = 0, linetype="dashed", alpha=0.5)+
  labs(x=NULL, y="Log Fold Change (Bacteroidetes - Firmicutes)")+coord_flip()+
  scale_fill_discrete(name="")+
  scale_x_discrete(limits = c("MA - VEN", "VEN - US", "MA - US"))+
  theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black"))+
  geom_text(aes(y=log.fold.change+2.5*sign(log.fold.change), label=star), 
            vjust=.7, color="black", position=position_dodge(width = .5))
ggarrange(p2, labels = "b")
ggsave("C:/Users/user/Figure 6b.pdf", width=6.25, height=5, units='in')
ggsave("C:/Users/user/Figure 6b.jpeg", width=6.25, height=5, units='in', dpi = 300)
```

## 3.4 Fig.6

```{r, message=FALSE, warning=FALSE, comment=NA, fig.width=12, fig.height=5}
p = ggarrange(p1, p2,
              labels = c("a", "b"), 
              ncol = 2, nrow = 1, widths = c(2, 1),
              common.legend = TRUE, legend="bottom")
p
ggsave("C:/Users/user/Desktop/Figure 6.pdf", width=12, height=5, units='in')
ggsave("C:/Users/user/Desktop/Figure 6.jpeg", width=12, height=5, units='in', dpi = 300)
```

# Session information

```{r, message=FALSE, warning=FALSE, comment=NA}
sessionInfo()
devtools::session_info()
```